# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            The Monastery at the End of the World
tagline:          'Lokantavihāra'
description:      'A little place for Bhante Sujato to stay, practice, and work on SuttaCentral'
url:              https://lokanta.github.io/
baseurl:           https://lokanta.github.io/

author:
  name:           'Bhikkhu Sujato'
  url:            https://suttacentral.net/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lokanta

theme: jekyll-theme-minimal
